#!/bin/bash

cp ../02.martinize_prot/NH2-Gly_CG.gro .

gmx make_ndx -f NH2-Gly_CG.gro << EOF
del 1-20
a BB & r 177-216
a BB & r 1-30
1 | 2
q
EOF

echo 3 0 | gmx editconf -f NH2-Gly_CG.gro -o NH2-Gly_CG_aligned.gro -n index.ndx -center `tail -1 ../03.vesicle_box/membrane_box.gro | awk '{print $1/2, $2/2, 3}'`  -c

touch DONE
