#!/bin/bash

gmx editconf -f ../01.strech_pore/min.gro -o membrane_box.gro -box 36 36 50  -c || exit 1
awk '/POP[CE]/ || /CHOL/ {printf "%s%8.3f%8.3f%8.3f\n", substr($0, 1, 20), 18, 18, 25; next} {print}' membrane_box.gro > ref.gro

touch DONE
