#!/bin/bash

export GMX_MAXCONSTRWARN=-1

i=1
cp min.gro conf${i}.gro
for PARMS in 0.0001:250000 0.001:50000 0.005:50000 0.01:50000 0.02:50000; do
    if [ ${i} -eq 1 ]; then VEL="yes"; else VEL="no"; CPT="-t conf${i}.cpt"; fi

    P=(`tr ":" " " <<< ${PARMS}`)
    sed "s/<nsteps>/${P[1]}/g; s/<dt>/${P[0]}/g; s/<vel>/${VEL}/g" martini_v2.x_new-rf.mdp > npt${i}.mdp

    gmx grompp -f npt${i}.mdp -n index.ndx -c conf${i}.gro -p complex.top ${CPT} -o npt${i}.tpr -maxwarn 1 || exit 1
    gmx mdrun -rdd 1.6 -deffnm npt${i} -v || exit 1

    cp npt${i}.gro conf$((i+1)).gro
    cp npt${i}.cpt conf$((i+1)).cpt

    i=$((i+1))
done

rm -f \#*
